services:  
  - type: worker  
    name: movie-twitter-bot  
    env: docker  
    dockerfilePath: ./Dockerfile  
    envVars:  
      - key: TWITTER_CONSUMER_KEY  
        sync: false  
      - key: TWITTER_CONSUMER_SECRET  
        sync: false  
      - key: TWITTER_ACCESS_TOKEN  
        sync: false  
      - key: TWITTER_ACCESS_TOKEN_SECRET  
        sync: false  
      - key: OMDB_API_KEY  
        sync: false  
      - key: TWEET_INTERVAL  
        value: 3600